{
  "name": "nodejs-throw-new-error",
  "version": "1.0.0",
  "description": "Lançando erros",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/flaviomicheletti/nodejs-throw-new-error.git"
  },
  "author": "Flávio Micheletti",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/flaviomicheletti/nodejs-throw-new-error/issues"
  },
  "homepage": "https://github.com/flaviomicheletti/nodejs-throw-new-error#readme",
  "dependencies": {
    "express": "^4.17.1"
  }
}
